### ISSUE TITLE
The linked form is dead.

### ISSUE THREAD

**Issue by stippi** [apgreimann/haiku-computer-list#1]
Subject says it all. I wanted to submit a working system, found this project, but it says not to open a PR. (Why not, btw?)

**Comment by apgreimann** [comment]
Hey there,

So usually there’s a Google form for putting in new hardware but I’ve
disabled it for now so there’s not new entries on top of the ones in the
site. I’ve been working on new ideas for the site to make it better (you’ll
notice the site mentions its being updated as well). Beyond a thread when I
first started on this I haven’t been keeping the community updated since
but my plans are to have it back up and ready with R1/Beta3, or the end of
February (if Haiku’s Beta3 timeline
https://dev.haiku-os.org/milestone/R1/beta3 is off).

And as far as the no pull requests or edits this is because there’s been
edit requests for the Google spreadsheet in the past; it helps protect the
results from contributors that’s in the lists to do it this way. However,
if the project gets to where it needs multiple maintainers I’ll probably
ask on the forum.

Hope this helps; sorry for the confusion!
